### ISSUE TITLE
Future composer require taocomp/php-e-invoice-it

### ISSUE THREAD

**Issue by MwSpaceLLC** [taocomp/php-e-invoice-it#1]
Ciao Ale!

Senti ma se aggiungessi la tua distro su https://packagist.org/ ?
Così potremmo scaricare e gestire aggiornamenti tramite composer require taocomp/php-e-invoice-it =)

**Comment by aded** [comment]
Spero di poter chiudere l'issue in giornata... ;-)

**Comment by aded** [comment]
Versione 0.1 per ora :-)
`composer require taocomp/php-e-invoice-it ^0.1`
