### ISSUE TITLE
validate

### ISSUE THREAD

**Issue by francescosganga** [taocomp/php-e-invoice-it#11]
Buongiorno,

cercando di validare la fattura, usando $invoice->validate(), ricevo un fatal error quando ovviamente l'xml non è valido, ma questo mi blocca tutto lo script. Non dovrebbe tornare "false" $invoice->validate()?

Grazie

**Comment by MwSpaceLLC** [comment]
Prova a sorvolare con una **Custom Exception** 
```
try {
$invoice->validate()
} catch (\Exception $exception) {
 return false
}
```
Se non va, prova a levare la root assoluta:
```
try {
$invoice->validate()
} catch (Exception $exception) {
 return false
}
```

**Comment by aded** [comment]
Ciao Francesco, certo, a pomeriggio pusho un aggiornamento: grazie per la segnalazione!

**Comment by francescosganga** [comment]
Colpa mia, doveva essere ovvio ma non mi è proprio venuto in mente! Grazie!

**Comment by aded** [comment]
@francescosganga Scusa avevo letto male, ovviamente la risposta di @MwSpaceLLC è corretta... :-)
Devi gestire tu l'eccezione, hai anche a disposizione il messaggio d'errore:

```
try {
// ...
$invoice->validate();
// ...
}
catch (\Exception $e) {
echo $e->getMessage();
}

```
