### ISSUE TITLE
Taocomp\Einvoicing\AbstractDocument::setValue(): unterminated entity reference C.

### ISSUE THREAD

**Issue by MwSpaceLLC** [taocomp/php-e-invoice-it#12]
Ciao ale, scusa ancora.
Oggi abbiamo riscontrato questo ISSUE:
Se mettiamo come ragione sociale dei dati con caratteri speciali : 
```
"CedentePrestatore/DatiAnagrafici"
array:5 [▼
  "IdFiscaleIVA/IdPaese" => "IT"
  "IdFiscaleIVA/IdCodice" => "00000000000"
  "CodiceFiscale" => "00000000000"
  "Anagrafica/Denominazione" => "TELONERIA EUGUBINA SNC DI CERBELLA F. & C."
  "RegimeFiscale" => "RF01"
]
```

Per correggere il bug, abbiamo dovuto rimuovere i caratteri speciali (. & .):
```
"CedentePrestatore/DatiAnagrafici"
array:5 [▼
  "IdFiscaleIVA/IdPaese" => "IT"
  "IdFiscaleIVA/IdCodice" => "00000000000"
  "CodiceFiscale" => "00000000000"
  "Anagrafica/Denominazione" => preg_replace("/[^a-zA-Z ]/", "", "TELONERIA EUGUBINA SNC DI CERBELLA F. & C.")
  "RegimeFiscale" => "RF01"
]
```
Potresti aggiornare anche questo ? 😘😘

**Comment by aded** [comment]
Hai provato a controllare l'XML qui?
[](https://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/AccediAlServizioAction.do?pagina=controlla_fattura)

I caratteri non alfanumerici non sembrano essere supportati. Nel tuo caso, `&` non va bene, il punto invece sì (e riesco a generare correttamente l'XML con i punti nella Denominazione, perché li rimuovi?).

Fammi sapere! :-)

**Comment by MwSpaceLLC** [comment]
Ok man 🐱‍🚀!
Abbiamo optato per la rimozione forzata almeno non abbiamo problemi. Susa l'inconveniente.
