### ISSUE TITLE
Invoice 1.5 schema support

### ISSUE THREAD

**Issue by albertovincenzi** [taocomp/php-e-invoice-it#15]
As far as I understand, this module support the 1.2 format.
Are you going to support also new 1.5 and maybe 1.6 (that should be released within this year?)

If I try to validate current generated xml with validate() function, I get
`DOMDocument::schemaValidateSource(): Invalid Schema`

**Comment by mircobabini** [comment]
Deduco che questo repo sia abbandonato. @albertovincenzi suggerimenti? Hai migrato ad altro?

**Comment by albertovincenzi** [comment]
Ciao @mircobabini,
in realtà, se non hai particolari esigenze dettate dalle nuove versioni, il modulo dovrebbe funzionare correttamente.
Al limite si potrebbe fare un fork per implementare quelle funzioni che non sono presenti oggi nella versione 1.2.

Io devo dire che con la versione 1.2 si coprono già la maggiorparte dei casi.

**Comment by aded** [comment]
> Deduco che questo repo sia abbandonato. @albertovincenzi suggerimenti? Hai migrato ad altro?

Torno a metterci mano a novembre per il nuovo formato, oltre che per gli issues e un'immagine Docker.

**Comment by Mark-81** [comment]
Buongiorno, ci sono aggiornamenti sul supporto del nuovo formato? Dal 1/1/2021 sarà obbligatorio l'1.6.1 e non verranno più accettati formati precedenti, rendendo di fatto inutilizzabile tutto il pregevole lavoro svolto fin qui!

**Comment by aded** [comment]
> Buongiorno, ci sono aggiornamenti sul supporto del nuovo formato? Dal 1/1/2021 sarà obbligatorio l'1.6.1 e non verranno più accettati formati precedenti, rendendo di fatto inutilizzabile tutto il pregevole lavoro svolto fin qui!

Previsto aggiornamento entro fine anno.

**Comment by albertovincenzi** [comment]
@aded, puoi avere bisogno di una mano per l'aggiornamento? Eventualmente ci possiamo sentire per vedere come fare...

**Comment by aded** [comment]
> @aded, puoi avere bisogno di una mano per l'aggiornamento? Eventualmente ci possiamo sentire per vedere come fare...

@albertovincenzi grazie mille, questo pomeriggio vorrei valutare il da farsi almeno per passare alla versione 1.6.2. C'è un link con un - rapido - sunto delle modifiche, al di là del doc di specifiche?

**Comment by albertovincenzi** [comment]
@aded dovendo partire dalla versione 1.2 alla 1.6.2, un po' di modifiche ci sono sicuramente...
Nel file delle specifiche, mi sembra ci sia un riassunto abbastanza chiaro, per chi ne mastica.

Io avevo visto anche questo link: https://guide.pec.it/fatturazione-elettronica/nuove-specifiche-tecniche/nuovo-tracciato-xml.aspx

**Comment by aded** [comment]
OK, sto aggiornando i vari tag XML (var ```templateArray``` in FatturaElettronica.php), poi pusherò nel branch "tracciato-v1.6.2" creato da poco. Esempi e tests non funzioneranno subito, comincerò a sistemarli subito dopo. Poi mi serve un modo per testare rapidamente le fatture in XML.

**Comment by albertovincenzi** [comment]
Potremmo provare a generarne qualcuna e ad importarla in qualche gestionale. In genere viene fatto un test all'importazione.
Chiaramente sarà difficile fare tutti i test del caso e non mi risulta ci sia un validatore aggiornato per le fatture. @Slamdunk mi sembrava avesse fatto qualcosa, ma temo si sia fermato alla 1.2.1

**Comment by aded** [comment]
@albertovincenzi ho fatto un primo push col ```templateArray``` aggiornato e un esempio di invoice. Adesso provo a generare un XML completo e provo a validarlo direttamente sul sito dell'AE. PR sul branch "tracciato-v1.6.2" sono apprezzati. :-)

**Comment by aded** [comment]
> @albertovincenzi ho fatto un primo push col `templateArray` aggiornato e un esempio di invoice. Adesso provo a generare un XML completo e provo a validarlo direttamente sul sito dell'AE. PR sul branch "tracciato-v1.6.2" sono apprezzati. :-)

Temo di aver preso in considerazione la fattura semplificata... :facepalm:

**Comment by Slamdunk** [comment]
Ogni pull-request è ben accetta sul mio repo, basta aggiornare l'XSD e rilascio subito una nuova versione

**Comment by aded** [comment]
@albertovincenzi in effetti la nuova versione è più impattante per la validazione che per la generazione dell'XML (questa libreria).
Manca al momento la possibilità di aggiungere l'attributo "SistemaEmittente", che è cmq facoltativo.
Il campo "BolloVirtuale" è stato aggiunto nel branch ```tracciato-v1.6.2```.

Al momento non è ovviamente opportuno utilizzare il metodo ```validate()``` finché non verrà coperta anche la nuova versione.

Io faccio qualche altro controllo con l'AE per verificare che gli XML generati siano validi, aggiungo ```SistemaEmittente``` e poi faccio il merge su master.

**Comment by albertovincenzi** [comment]
@aded magnifico. Io pensavo di mettermici su domani per fare qualche test. Non sono un espertone di fattura elettronica, quindi potrebbe essere un feedback limitato, ma meglio di nulla!

**Comment by Mark-81** [comment]
Ciao a tutti, vi ringrazio per l'impegno!
Perdonate la mia inesperienza, ma sto provando a fare qualche test. Ho aggiornato il codice e ho provato a rilanciare l'esportazione dell'xml dalla mia piccola app PHP.

Vedo però la stessa intestazione:

```
<?xml version="1.0" encoding="UTF-8"?>
<p:FatturaElettronica xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/Schema_del_file_xml_FatturaPA_versione_1.2.xsd" versione="FPR12">
```

e in effetti nel file:

https://github.com/taocomp/php-e-invoice-it/blob/tracciato-v1.6.2/src/FatturaElettronica.php

sono presenti i vecchi valori:

```
    const ROOT_NAMESPACE  = 'http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2';
    const SCHEMA_LOCATION = 'http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 '
                          . 'http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa'
                          . '/v1.2/Schema_del_file_xml_FatturaPA_versione_1.2.xsd';
```

E' corretto? Non sono un esperto, ma cosa differenzia il formato 1.2 dall'1.6 se non dall'intestazione. Voglio dire, a meno di utilizzare i nuovi campi, come farebbero (da domani) i validatori a scartare i formati 1.2?

**Comment by albertovincenzi** [comment]
Sto cercando di capire anche io perché la documentazione non fa riferimento a quei valori. Negli esempi, si riporta una versione 2.0, ma con riferimento allo "SCHEMA XSD TRASMISSIONE DATI FATTURE TRANSFRONTALIERE".
Sembrerebbe invece che la versione 1.6.2 della fattura sia contemplato nello schema 1.2.1

**Comment by albertovincenzi** [comment]
@aded ho fatto un controllo generale e mi sembra che ci siamo. Dovrebbe funzionare anche il validatore dato che già da ottobre avevano inserito lo schema 1.2.1 del tracciato. L'unica cosa è che ho provato a validare il tuo esempio e si pianta sull'intestazione con questo errore:
`DOMDocument::schemaValidateSource(): Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.w3.org/2000/09/xmldsig#}Signature' does not resolve to a(n) element declaration.`

**Comment by aded** [comment]
@albertovincenzi occhio ché io sto apportando le modifiche su un branch diverso da master, e la versione di composer è sempre la stessa. Una volta ok il codice, faccio il merge su master e conseguente aggiornamento via-composer.

@Mark-81 anch'io mi aspettavo un aggiornamento della versione. Come dice Alberto, sembra che si debba cmq mettere la versione 1.2.1. Ed è infatti una delle modifiche che devo fare prima del merge. Potrei avere difficoltà oggi, molto più probabile domani.

**Comment by albertovincenzi** [comment]
@aded assolutamente si. Infatti io ho provato sul branch 1.6.2.
Il problema non è il tuo codice, ma quello del pacchetto di validazione che sembra non funzionare su windows. Su linux invece dovrebbe girare bene e lo schema è aggiornato alla 1.2.1, quindi potrebbe essere perfetto per validare anche questa nuova versione
