### ISSUE TITLE
undefined method Taocomp\Einvoicing\FatturaElettronica::addElementsFrom

### ISSUE THREAD

**Issue by MwSpaceLLC** [taocomp/php-e-invoice-it#2]
Ciao Ale, scusa il disturbo...
Sto provando con il codice nel file Example.
A me ritorna : 
`Call to undefined method Taocomp\Einvoicing\FatturaElettronica::addElementsFromArray()`
Neanche l'editor mi trova la classe =(

Codice dell'errore:
```
            // Add elements
            // $FatturaElettronica->addElement('PECDestinatario', 'DatiTrasmissione');
            // $FatturaElettronica->setValue('PECDestinatario', 'pec@example.com');
            // Add elements from array
            $body = $FatturaElettronica->getBody();
            $datiGeneraliDocumento = $FatturaElettronica->getElement('DatiGeneraliDocumento', $body);
            $FatturaElettronica->addElementsFromArray($datiGeneraliDocumento, array(
                'DatiRitenuta' => array(
                    'TipoRitenuta' => '',
                    'ImportoRitenuta' => '23.00',
                    'AliquotaRitenuta' => ''
                )
            ));
```

**Comment by aded** [comment]
Probabilmente non ho aggiornato la versione. Cmq se aspetti un po' sto sistemando altre cose e sto aggiornando la documentazione (anche una versione in italiano).
Così elenco per bene tutte le features e come si fa cosa. Giusto qualche ora e pusho tutto.

**Comment by MwSpaceLLC** [comment]
Sei un grande! non vedo l'ora di farti vedere il nostro movimento.
Web App -> Laravel 🤯
IOS/Android -> React Native 😎
Price -> 100% free 😅
Copyright -> All Vendor Creator & linking on github 🤩

**Comment by aded** [comment]
Ho aggiornato release e aggiunto README.it.org con un po' di documentazione. Domani aggiungo degli esempi completi con più body e più linee di dettaglio. `addElementsFromArray` dell'esempio adesso dovrebbe funzionarti, ma è più opportuno chiamare `setValuesFromArray`, descritta in README.it.org.
Comunque non appena aggiornerò gli esempi sarà tutto più chiaro spero! :-)

**Comment by MwSpaceLLC** [comment]
Ciao ale, scusa tanto il disturbo...
sto provando i nuovi example,
**php-e-invoice-it/examples/FPR12-many-line-items.php**
xml output funziona bene, ma in fondo alla pagina,dopo xml, appare : 

<p:FatturaElettronica>CONTENT</p:FatturaElettronica>
| Element not found (FatturaElettronicaBody[2])

**Comment by aded** [comment]
Ciao Alex nessun disturbo anzi apri tutti gli issue del caso. :-)
Sì il foreach dovrebbe andar bene così, più tardi in ogni caso faccio un esempio con più body.
Intanto chiudo questo, ma ripeto: aprine altri se qualcosa non va, o anche se è poco chiara, così sistemo la doc. :-)

**Comment by MwSpaceLLC** [comment]
ok grazie 😅.

Comunque lo sai cosa sarebbe carino ? aggiungere una piccolissima libreria per mostrare gli xml con css.

esempio -> https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/fatturaPA_v1.2.1.xsl
esempio ->https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/fatturaordinaria_v1.2.1.xsl

src->https://www.fatturapa.gov.it/export/fatturazione/it/a-3.htm

ps. ricordati i dati per i json author + link 😎. Così ti possono poi contattare i visitatori del portale

**Comment by aded** [comment]
> Comunque lo sai cosa sarebbe carino ? aggiungere una piccolissima libreria per mostrare gli xml con css.
> 
> esempio -> https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/fatturaPA_v1.2.1.xsl
> esempio ->https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/fatturaordinaria_v1.2.1.xsl
> 
> src->https://www.fatturapa.gov.it/export/fatturazione/it/a-3.htm

La visualizzazione mediante fogli di stile esula dai compiti della libreria, però nell'XML delle notifiche è già presente il tag
`<?xml-stylesheet type="text/xsl" href="EC_v1.0.xsl"?>`
(anche se devo modificare l'href mi sa).
Posso aggiungere l'equivalente per le fatture se non dà problemi.

Apropos, la libreria è sempre stata testata con i formati FPA12 ed FPR12, sinora.

> ps. ricordati i dati per i json author + link sunglasses. Così ti possono poi contattare i visitatori del portale

Ho aggiunto il blocco `authors` a tutti e tre i repositories. :-)

**Comment by aded** [comment]
Ciao Alex,

ho aggiunto un esempio per il lotto di fatture. L'XML è valido (a parte le somme degli importi nei dati riepilogo). Fammi sapere! :-)

> Poi il body `$notice->setValuesFromInvoice()`
> Va settato a seconda della quantità di fatture nel file xml ?
> in questo caso io ho più linee e 1 solo body. giusto ?

Nella documentazione è scritto che in caso di lotto, le notifiche vanno inviate separatamente per ogni body (cioè per ogni fattura del lotto). Ecco perché c'è il secondo parametro, serve a specificare da quale body (fattura) si vogliono prendere i dati.
