### ISSUE TITLE
Aggiunta DatiRiepilogo[$i]

### ISSUE THREAD

**Issue by MwSpaceLLC** [taocomp/php-e-invoice-it#5]
Stavo provando a generare più linee, ed ho visto che in alcuni file xml di altri programmi, ci sono i 

i DatiRiepilogo quante volte sono le DettaglioLinee. ho provato questo, ma non va =(

```
            foreach ($invoice->field()->get() as $key => $field) {
                // Dettaglio Linee
                $FatturaElettronica->setValues('DettaglioLinee[' . ($key > 0 ? $key : 1) . ']', array(
                    'NumeroLinea' => ($key > 0 ? $key : 1),
                    'Descrizione' => $field->description,
                    'Quantita' => $field->quantity . '.00',
                    'PrezzoUnitario' => $field->amount,
                    'PrezzoTotale' => $field->total,
                    'AliquotaIVA' => $field->vat . '.00',
                ));
                // Dati Riepilogo
                $FatturaElettronica->setValues('DatiRiepilogo[' . ($key > 0 ? $key : 1) . ']', array(
                    'AliquotaIVA' => $field->vat . '.00',
                    'ImponibileImporto' => $field->total,
                    'Imposta' => $field->total_vat,
                    'EsigibilitaIVA' => ($invoice->split_pyment > 0) ? 'S' : 'I'
                ));
            }
```

**Comment by aded** [comment]
Occhio ché i DatiRiepilogo non sono in relazione 1-1 con DettaglioLinee. Dal PDF delle specifiche tecniche:

> DATI DI RIEPILOGO - I campi che contiene si ripetono per ogni aliquota e modalità di versamento
dell’imposta diversa (“scissione dei pagamenti” od ordinaria) o per natura diversa.
Ne deriva una molteplicità da 0 ad N.

Più tardi comunque aggiungo un metodo per settare la molteplicità di un elemento, come per DettaglioLinee (qualcosa tipo `setElementCount()`).

Finisco prima con gli stylesheet, stay tuned. :-)

**Comment by MwSpaceLLC** [comment]
😢 scusa, allora mi sbagliavo...
allora attendo l'update per aggiungere il dettaglio riepilogo, perchè questo succede se un utente 😤fa una fattura con aliquote diverse.. vanno specificate con più campi.

comunque vedi che ti si vede adesso ??😜
![image](https://user-images.githubusercontent.com/29952045/50525063-94ac1f80-0ad9-11e9-8fc0-5c72570bcf21.png)

**Comment by aded** [comment]
v0.1.6:

Aggiunto metodo `setElementCount($expr, $count, $context = null)`

In `examples/invoice.php` c'è un esempio:

```
    // 2 DatiRiepilogo for second body
    $invoice->setElementCount('DatiRiepilogo', 2, $body2);
    $invoice->setValue('DatiRiepilogo[1]/AliquotaIVA', '22.00', $body2);
    $invoice->setValue('DatiRiepilogo[2]/AliquotaIVA', '10.00', $body2);

```

Però devo fare un po' di refactoring un giorno di questi... :-)

Spero di vedere la piattaforma in funzione quanto prima! :-)
